### ISSUE TITLE
getInfo deprecation

### ISSUE THREAD

**Issue by mattdy** [mattdy/nagios-bitcoin#1]
In v0.16, the 'getInfo' RPC command will be removed - https://github.com/bitcoin/bitcoin/issues/11054

This script will need to use the separated commands 'getblockchaininfo', 'getnetworkinfo', and 'getwalletinfo' as necessary.

**Comment by bitlewis** [comment]
I submitted a Pull request with a solution to this issue.

However, had to get rid of the "error" check type.

**Comment by mattdy** [comment]
Thanks for the PR, sorry it's taken so long! I've merged your changes and made a few of my own, so this should now be complete.
